# # Generated by Django 4.2.6 on 2023-10-24 01:20

# from django.db import migrations, models
# import django.db.models.deletion


# class Migration(migrations.Migration):

#     initial = True

#     dependencies = [
#         ('province', '0001_initial'),
#         ('bar', '0001_initial'),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='Bar_Amusement',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('bar_amusement_title', models.CharField(max_length=50)),
#                 ('bar_amusement_eid', models.CharField(max_length=30)),
#                 ('bar_amusement_description', models.TextField()),
#             ],
#         ),
#         migrations.CreateModel(
#             name='Bar_Category',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('bar_category_title', models.CharField(max_length=30)),
#                 ('bar_category_eid', models.CharField(max_length=30)),
#                 ('bar_category_description', models.TextField()),
#             ],
#         ),
#         migrations.CreateModel(
#             name='Bar_Facility',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('bar_facility_title', models.CharField(max_length=30)),
#                 ('bar_facility_eid', models.CharField(max_length=30)),
#                 ('bar_facility_description', models.TextField()),
#             ],
#         ),
#         migrations.CreateModel(
#             name='PaymentMethod',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('paymentmethod_title', models.CharField(max_length=50)),
#                 ('paymentmethod_eid', models.CharField(max_length=50)),
#                 ('paymentmethod_description', models.TextField()),
#             ],
#         ),
#         migrations.CreateModel(
#             name='Bar',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('bar_title', models.CharField(max_length=120)),
#                 ('bar_eid', models.CharField(max_length=40, null=True)),
#                 ('bar_position', models.TextField(null=True)),
#                 ('bar_description', models.TextField(null=True)),
#                 ('bar_vorder', models.IntegerField(null=True)),
#                 # ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='province.province')),
#             ],
#         ),
#     ]
