# Generated by Django 4.2.6 on 2023-10-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_title', models.CharField(max_length=120)),
                ('area_eid', models.CharField(max_length=30, null=True)),
                ('area_description', models.CharField(max_length=120)),
                ('area_vorder', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_title', models.CharField(max_length=120)),
                ('province_eid', models.CharField(max_length=30, null=True)),
                ('province_description', models.TextField()),
                ('province_vorder', models.IntegerField(null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='province.area')),
            ],
        ),
    ]
