# Generated by Django 4.2.6 on 2023-10-24 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('province', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_title', models.CharField(max_length=120)),
                ('bar_eid', models.CharField(max_length=40, null=True)),
                ('bar_position', models.TextField(null=True)),
                ('bar_description', models.TextField(null=True)),
                ('bar_vorder', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bar_Amusement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_amusement_title', models.CharField(max_length=50)),
                ('bar_amusement_eid', models.CharField(max_length=30)),
                ('bar_amusement_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bar_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_category_title', models.CharField(max_length=30)),
                ('bar_category_eid', models.CharField(max_length=30)),
                ('bar_category_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bar_Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_facility_title', models.CharField(max_length=30)),
                ('bar_facility_eid', models.CharField(max_length=30)),
                ('bar_facility_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_name', models.CharField(default='', max_length=30)),
                ('cast_sex', models.IntegerField(default=0)),
                ('cast_birthday', models.DateField(null=True)),
                ('cast_phone', models.CharField(max_length=30, null=True)),
                ('cast_description', models.CharField(max_length=100, null=True)),
                ('cast_address', models.CharField(default='', max_length=100)),
                ('cast_barid', models.IntegerField(default=0)),
                ('cast_height', models.FloatField(null=True)),
                ('cast_weight', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentmethod_title', models.CharField(max_length=50)),
                ('paymentmethod_eid', models.CharField(max_length=50)),
                ('paymentmethod_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bars_Casts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_recorddate', models.DateField()),
                ('bar_expiredate', models.DateField()),
                ('bar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bars.bar')),
                ('cast_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bars.cast')),
            ],
        ),
        migrations.AddField(
            model_name='bar',
            name='fk_amusements',
            field=models.ManyToManyField(to='bars.bar_amusement'),
        ),
        migrations.AddField(
            model_name='bar',
            name='fk_casts',
            field=models.ManyToManyField(through='bars.Bars_Casts', to='bars.cast'),
        ),
        migrations.AddField(
            model_name='bar',
            name='fk_categorys',
            field=models.ManyToManyField(to='bars.bar_category'),
        ),
        migrations.AddField(
            model_name='bar',
            name='fk_facilitys',
            field=models.ManyToManyField(to='bars.bar_facility'),
        ),
        migrations.AddField(
            model_name='bar',
            name='fk_paymentmethods',
            field=models.ManyToManyField(to='bars.paymentmethod'),
        ),
        migrations.AddField(
            model_name='bar',
            name='fk_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='province.province', verbose_name='select province'),
        ),
    ]
