# Generated by Django 4.2.6 on 2023-10-24 14:08

import admin_kit.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='cast_sex',
            field=admin_kit.models.SelectField(ajax_source=None, choices=[(0, 'male'), (1, 'female')], default_value=None, identifier=None, kit_config={}, source_router=None),
        ),
    ]
