# Generated by Django 4.2.6 on 2023-10-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0002_alter_cast_cast_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='cast_description',
            field=models.TextField(null=True),
        ),
    ]
