# Generated by Django 4.2.6 on 2023-10-24 14:24

import admin_kit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0003_alter_cast_cast_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='cast_phone',
        ),
        migrations.AddField(
            model_name='cast',
            name='cast_homephone',
            field=models.CharField(max_length=30, null=True, verbose_name='home phone number'),
        ),
        migrations.AddField(
            model_name='cast',
            name='cast_mobilephone',
            field=models.CharField(max_length=30, null=True, verbose_name='mobile phone number'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='bar_description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='bar_eid',
            field=models.CharField(max_length=40, null=True, verbose_name='bar name (English)'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='bar_position',
            field=models.TextField(null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='bar_title',
            field=models.CharField(max_length=120, verbose_name='bar name'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='bar_vorder',
            field=models.IntegerField(null=True, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='bar_amusement',
            name='bar_amusement_description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='bar_amusement',
            name='bar_amusement_eid',
            field=models.CharField(max_length=30, verbose_name='amusement (English)'),
        ),
        migrations.AlterField(
            model_name='bar_amusement',
            name='bar_amusement_title',
            field=models.CharField(max_length=50, verbose_name='amusement type'),
        ),
        migrations.AlterField(
            model_name='bar_category',
            name='bar_category_description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='bar_category',
            name='bar_category_eid',
            field=models.CharField(max_length=30, verbose_name='category (English)'),
        ),
        migrations.AlterField(
            model_name='bar_category',
            name='bar_category_title',
            field=models.CharField(max_length=30, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='bar_facility',
            name='bar_facility_description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='bar_facility',
            name='bar_facility_eid',
            field=models.CharField(max_length=30, verbose_name='facility (English)'),
        ),
        migrations.AlterField(
            model_name='bar_facility',
            name='bar_facility_title',
            field=models.CharField(max_length=30, verbose_name='facility type'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_address',
            field=models.CharField(default='', max_length=100, verbose_name='home address'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_barid',
            field=models.IntegerField(default=0, verbose_name='belonging bar'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_birthday',
            field=models.DateField(null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_height',
            field=models.FloatField(null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_name',
            field=models.CharField(default='', max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_sex',
            field=admin_kit.models.SelectField(ajax_source=None, choices=[(0, 'male'), (1, 'female')], default_value=None, identifier=None, kit_config={}, source_router=None, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_weight',
            field=models.FloatField(null=True, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='paymentmethod_description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='paymentmethod_eid',
            field=models.CharField(max_length=50, verbose_name='payment method (English)'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='paymentmethod_title',
            field=models.CharField(max_length=50, verbose_name='payment method'),
        ),
    ]
