# Generated by Django 4.2.6 on 2023-10-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0004_remove_cast_cast_phone_cast_cast_homephone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='cast_barid',
        ),
    ]
