# Generated by Django 4.2.6 on 2023-10-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0005_remove_cast_cast_barid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='cast_barid',
            field=models.IntegerField(default=0, verbose_name='belonging bar'),
        ),
    ]
