# Generated by Django 4.2.6 on 2023-10-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0006_cast_cast_barid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='cast_barid',
        ),
        migrations.AddField(
            model_name='cast',
            name='fk_bars',
            field=models.ManyToManyField(through='bars.Bars_Casts', to='bars.bar'),
        ),
    ]
