# Generated by Django 4.2.6 on 2023-10-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0008_alter_bars_casts_bar_expiredate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='bar_description',
            field=models.TextField(null=True, verbose_name='現時点で'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='bar_vorder',
            field=models.IntegerField(null=True, verbose_name='現時点で'),
        ),
        migrations.AlterField(
            model_name='bar_amusement',
            name='bar_amusement_description',
            field=models.TextField(verbose_name='現時点で'),
        ),
        migrations.AlterField(
            model_name='bar_amusement',
            name='bar_amusement_eid',
            field=models.CharField(max_length=30, verbose_name='アミューズメント (English)'),
        ),
        migrations.AlterField(
            model_name='bar_amusement',
            name='bar_amusement_title',
            field=models.CharField(max_length=50, verbose_name='アミューズメント'),
        ),
        migrations.AlterField(
            model_name='bar_category',
            name='bar_category_description',
            field=models.TextField(verbose_name='現時点で'),
        ),
        migrations.AlterField(
            model_name='bar_category',
            name='bar_category_eid',
            field=models.CharField(max_length=30, verbose_name='ジャンル (English)'),
        ),
        migrations.AlterField(
            model_name='bar_category',
            name='bar_category_title',
            field=models.CharField(max_length=30, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='bar_facility',
            name='bar_facility_description',
            field=models.TextField(verbose_name='現時点で'),
        ),
        migrations.AlterField(
            model_name='bar_facility',
            name='bar_facility_eid',
            field=models.CharField(max_length=30, verbose_name='施設タイプ (English)'),
        ),
        migrations.AlterField(
            model_name='bar_facility',
            name='bar_facility_title',
            field=models.CharField(max_length=30, verbose_name='施設タイプ'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_description',
            field=models.TextField(null=True, verbose_name='現時点で'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='paymentmethod_description',
            field=models.TextField(verbose_name='現時点で'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='paymentmethod_eid',
            field=models.CharField(max_length=50, verbose_name='支払い方法 (English)'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='paymentmethod_title',
            field=models.CharField(max_length=50, verbose_name='支払い方法'),
        ),
    ]
