# Generated by Django 4.2.6 on 2023-10-24 17:51

import admin_kit.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0003_alter_area_area_description_alter_area_area_eid_and_more'),
        ('bars', '0009_alter_bar_bar_description_alter_bar_bar_vorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='bar_eid',
            field=models.CharField(max_length=40, null=True, verbose_name='キャスト名・店舗名 (English)'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='bar_position',
            field=models.TextField(null=True, verbose_name='場所'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='bar_title',
            field=models.CharField(max_length=120, verbose_name='キャスト名・店舗名'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='fk_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='province.province', verbose_name='都道府県選択'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_address',
            field=models.CharField(default='', max_length=100, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_birthday',
            field=models.DateField(null=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_height',
            field=models.FloatField(null=True, verbose_name='キー'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_homephone',
            field=models.CharField(max_length=30, null=True, verbose_name='家電番号'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_mobilephone',
            field=models.CharField(max_length=30, null=True, verbose_name='携帯電話番号'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_name',
            field=models.CharField(default='', max_length=30, verbose_name='キャスト名'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_sex',
            field=admin_kit.models.SelectField(ajax_source=None, choices=[(0, 'male'), (1, 'female')], default_value=None, identifier=None, kit_config={}, source_router=None, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_weight',
            field=models.FloatField(null=True, verbose_name='体重'),
        ),
    ]
