# Generated by Django 4.2.6 on 2023-10-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0011_rename_bars_casts_bar_fk_casts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bar_fk_casts',
            old_name='bar_id',
            new_name='bar',
        ),
        migrations.RenameField(
            model_name='bar_fk_casts',
            old_name='cast_id',
            new_name='cast',
        ),
    ]
