# Generated by Django 4.2.6 on 2023-10-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0012_rename_bar_id_bar_fk_casts_bar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='cast_blood',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='cast',
            name='cast_horoscope',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
