# Generated by Django 4.2.6 on 2023-10-28 13:56

import admin_kit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0013_cast_cast_blood_cast_cast_horoscope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='cast_birthday',
            field=models.DateField(null=True, verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_blood',
            field=admin_kit.models.SelectField(ajax_source=None, choices=[(0, 'O型'), (1, 'A型'), (2, 'B型'), (3, 'AB型')], default=0, default_value=0, identifier=None, kit_config={}, source_router=None, verbose_name='血液型'),
        ),
    ]
