# Generated by Django 4.2.6 on 2023-10-29 04:08

import admin_kit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0014_alter_cast_cast_birthday_alter_cast_cast_blood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='cast_height',
            field=models.FloatField(null=True, verbose_name='身長'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_sex',
            field=admin_kit.models.SelectField(ajax_source=None, choices=[(0, '男'), (1, '女')], default_value=None, identifier=None, kit_config={}, source_router=None, verbose_name='性別'),
        ),
    ]
